config/routes.rb
Fixit::Application.routes.draw do
  resources :damages

  resources :fixit_tests

  root 'home#index'

  

end

app/models/damage.rb
class Damage < ActiveRecord::Base
	attr_accessible :category, :details, :url, :location
end

app/models/fixit_test.rb
class FixitTest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/damages_controller.rb
class DamagesController < ApplicationController
  before_action :set_damage, only: [:show, :edit, :update, :destroy]

  # GET /damages
  # GET /damages.json
  def index
    @damages = Damage.all
  end

  # GET /damages/1
  # GET /damages/1.json
  def show
  end

  # GET /damages/new
  def new
    @damage = Damage.new
  end

  # GET /damages/1/edit
  def edit
  end

  # POST /damages
  # POST /damages.json
  def create
    puts '----------------------------', params
    @damage = Damage.new(params[:damage])

    respond_to do |format|
      if @damage.save
        format.html { redirect_to @damage, notice: 'Damage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @damage }
      else
        format.html { render action: 'new' }
        format.json { render json: @damage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /damages/1
  # PATCH/PUT /damages/1.json
  def update
    respond_to do |format|
      if @damage.update(params)
        format.html { redirect_to @damage, notice: 'Damage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @damage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /damages/1
  # DELETE /damages/1.json
  def destroy
    @damage.destroy
    respond_to do |format|
      format.html { redirect_to damages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_damage
      @damage = Damage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def damage_params
      params.require(:damage).permit(:type, :details, :url, :location)
    end
end

app/controllers/fixit_tests_controller.rb
class FixitTestsController < ApplicationController
  before_action :set_fixit_test, only: [:show, :edit, :update, :destroy]

  # GET /fixit_tests
  # GET /fixit_tests.json
  def index
    @fixit_tests = FixitTest.all
  end

  # GET /fixit_tests/1
  # GET /fixit_tests/1.json
  def show
  end

  # GET /fixit_tests/new
  def new
    @fixit_test = FixitTest.new
  end

  # GET /fixit_tests/1/edit
  def edit
  end

  # POST /fixit_tests
  # POST /fixit_tests.json
  def create
    @fixit_test = FixitTest.new(fixit_test_params)

    respond_to do |format|
      if @fixit_test.save
        format.html { redirect_to @fixit_test, notice: 'Fixit test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fixit_test }
      else
        format.html { render action: 'new' }
        format.json { render json: @fixit_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fixit_tests/1
  # PATCH/PUT /fixit_tests/1.json
  def update
    respond_to do |format|
      if @fixit_test.update(fixit_test_params)
        format.html { redirect_to @fixit_test, notice: 'Fixit test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fixit_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixit_tests/1
  # DELETE /fixit_tests/1.json
  def destroy
    @fixit_test.destroy
    respond_to do |format|
      format.html { redirect_to fixit_tests_url }
      format.json { head :no_content }
    end
  end

  def home

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fixit_test
      @fixit_test = FixitTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fixit_test_params
      params.require(:fixit_test).permit(:type, :details, :email, :location, :picture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_navbar
		render :partial=>'common/navbar'
	end


	# renders an alert message
	# alert_type (String) can be one of alert-success, 
	# alert-info, alert-warning, alert-danger
	def render_notice(title, message, alert_type="alert-info")
		alert_types = ["alert-success", "alert-info", "alert-warning", "alert-danger"]
		raise ArgumentError, "alert_type must be one of #{alert_types}" unless alert_types.include? alert_type
		render :partial=>"common/flash",:locals=>{:title=>title,:alert_type=>alert_type,:message=>message}		
	end

end

app/helpers/damages_helper.rb
module DamagesHelper
end

app/helpers/fixit_tests_helper.rb
module FixitTestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/common/_flash.html.erb
<%#  %>
<div class="alert <%= alert_type %> alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><%= title %></strong> <%= message %>
</div>

app/views/common/_navbar.html.erb
  <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Fixit", "/",:class=>"navbar-brand"%>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Daños", damages_path,:class=>""%>
              </li>
              <li>
                <%= link_to "Reportar", new_damage_path,:class=>""%>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
  </div>

app/views/damages/_form.html.erb
<%= form_for(@damage) do |f| %>
<% if @damage.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@damage.errors.count, "error") %> prohibited this damage from being saved:</h2>

  <ul>
    <% @damage.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group-container">
  <%= f.label :category,:class=>"control-label col-lg-2" %>
  <div class="col-lg-10">
    <%= f.text_field :category,:class=>"form-control",:placeholder=>"" %>
  </div>
</div>

<div class="form-group-container">
  <%= f.label :url,:class=>"control-label col-lg-2" %>
  <div class="col-lg-10">
    <%= f.text_field :url,:class=>"form-control",:placeholder=>"" %>
  </div>
</div>
<div class="form-group-container">
  <%= f.label :details,:class=>"control-label col-lg-2" %>
  <div class="col-lg-10">
    <%= f.text_field :details,:class=>"form-control",:placeholder=>"Ingresa detalles sobre el daño: 'aveces el computador no prende' " %>
  </div>
</div>
<div class="form-group-container">
  <%= f.label :location,:class=>"control-label col-lg-2" %>
  <div class="col-lg-10">
    <%= f.text_field :location,:class=>"form-control",:placeholder=>"Ubica el daño con precicion: R503 o ML202, pupitre de la tercera fila" %>
  </div>
</div>

<div class="actions">
  <%= f.submit "enviar", :class=>"btn btn-primary",:style=>"margin-top:10px" %>
</div>
<% end %>

app/views/damages/edit.html.erb
<%= render_navbar %>

<h1>Editing damage</h1>

<%= render 'form' %>

<%= link_to 'Show', @damage %> |
<%= link_to 'Back', damages_path %>

app/views/damages/index.html.erb
  <%= render_navbar %>

  <!--<div class="container">-->

    <h1>Listing damages</h1>

    <% @damages.each do |dam|%>
    <div class="row">
      <div class="col-md-2">
        <img src=<%=dam.url%>>
      </div>
     <div class="col-md-8">
        <p>Categoría <%= dam.category%></p>
        <p>Detalles <%= dam.details%></p>
        <p>Ubicación <%= dam.location%></p>
        <p><%= link_to 'Editar', edit_damage_path(dam) %></p>
        <p><%= link_to 'Destroy', dam, method: :delete, data: { confirm: '¿Seguranzas?' } %></p>
      </div>
    </div>
    <%end%>

    <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Details</th>
          <th>Url</th>
          <th>Location</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @damages.each do |damage| %>
          <tr>
            <td><%= damage.category %></td>
            <td><%= damage.details %></td>
            <td><%= damage.url %></td>
            <td><%= damage.location %></td>
            <td><%= link_to 'Show', damage %></td>
            <td><%= link_to 'Edit', edit_damage_path(damage) %></td>
            <td><%= link_to 'Destroy', damage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!--<br>-->

    <%= link_to 'New Damage', new_damage_path %>

  </div>

app/views/damages/new.html.erb
<%= render_navbar %>
<div class="container">
	
	<h1>Reportar daño</h1>
	<p>Ayudanos a mejorar nuestra universidad, reporta los daños que veas!</p>

	<%= render 'form' %>

</div>

app/views/damages/show.html.erb
<%= render_navbar %>

<%= render_notice "",notice if notice %>

<p>
  <strong>Type:</strong>
  <%= @damage.category%>
</p>

<p>
  <strong>Details:</strong>
  <%= @damage.details %>
</p>

<p>
  <strong>Url:</strong>
  <%= @damage.url %>
</p>

<p>
  <strong>Location:</strong>
  <%= @damage.location %>
</p>

<%= link_to 'Edit', edit_damage_path(@damage) %> |
<%= link_to 'Back', damages_path %>

app/views/fixit_tests/_form.html.erb
<%= form_for(@fixit_test) do |f| %>
  <% if @fixit_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fixit_test.errors.count, "error") %> prohibited this fixit_test from being saved:</h2>

      <ul>
      <% @fixit_test.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fixit_tests/edit.html.erb
<h1>Editing fixit_test</h1>

<%= render 'form' %>

<%= link_to 'Show', @fixit_test %> |
<%= link_to 'Back', fixit_tests_path %>

app/views/fixit_tests/home.html.erb
<h1>Acá va el título de la página</h1>

app/views/fixit_tests/index.html.erb
<h1>Listing fixit_tests</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Details</th>
      <th>Email</th>
      <th>Location</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fixit_tests.each do |fixit_test| %>
      <tr>
        <td><%= fixit_test.type %></td>
        <td><%= fixit_test.details %></td>
        <td><%= fixit_test.email %></td>
        <td><%= fixit_test.location %></td>
        <td><%= fixit_test.picture %></td>
        <td><%= link_to 'Show', fixit_test %></td>
        <td><%= link_to 'Edit', edit_fixit_test_path(fixit_test) %></td>
        <td><%= link_to 'Destroy', fixit_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fixit test', new_fixit_test_path %>

app/views/fixit_tests/new.html.erb
<h1>New fixit_test</h1>

<%= render 'form' %>

<%= link_to 'Back', fixit_tests_path %>

app/views/fixit_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @fixit_test.type %>
</p>

<p>
  <strong>Details:</strong>
  <%= @fixit_test.details %>
</p>

<p>
  <strong>Email:</strong>
  <%= @fixit_test.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @fixit_test.location %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @fixit_test.picture %>
</p>

<%= link_to 'Edit', edit_fixit_test_path(@fixit_test) %> |
<%= link_to 'Back', fixit_tests_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li class="active">
        <%= link_to "Reportar", new_damage_path %>
      </li>
      <li>
        <%= link_to "Daños", damages_path %>
      </li>
    </ul>
    <h3 class="text-muted">Fixit <small>BETA</small> </h3>
  </div>

  <div class="jumbotron">
    <h1>Arreglemoslo!</h1>
    <p class="lead">Si alguna vez has visto alguna silla dañada, un mouse sin bolita o un teclado sin teclas y no sabes a quién avisarle para que lo arreglen, ahora puedes. Ayudanos a mejorar nuestra universidad.</p>
    <p>
      <%= link_to "Reporta un daño",new_damage_path, :class=>"btn btn-lg btn-success"%>
    </p>
  </div>

  <div class="row marketing">
    <div class="col-lg-6">
      <h4>Subheading</h4>
      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

      <h4>Subheading</h4>
      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

      <h4>Subheading</h4>
      <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>

    <div class="col-lg-6">
      <h4>Subheading</h4>
      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

      <h4>Subheading</h4>
      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

      <h4>Subheading</h4>
      <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
  </div>

  <div class="footer">
    <p>&copy; ACM-Uniandes 2013</p>
  </div>

</div> <!-- /container -->

app/views/home/index2.html.erb
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="http://getbootstrap.com/examples/carousel/#">Fixit</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</li>
                <li><a href="#about">Acerca de Fixit</a></li>
                <li><a href="#contact">¡Contáctanos!</a></li>
                <li class="dropdown">
                  <a href="/#" class="dropdown-toggle" data-toggle="dropdown">Acciones<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="http://getbootstrap.com/examples/carousel/#">Reportar Daño</a></li>
                    <li><a href="http://getbootstrap.com/examples/carousel/#">Reportar Bug</a></li>
                    <li><a href="http://getbootstrap.com/examples/carousel/#">Mapa</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Colaboradores</li>
                    <li><a href="http://acm.uniandes.edu.co">ACM Uniandes</a></li>
                    <li><a href="http://ceu1.uniandes.edu.co/wordpress">Consejo Estudiantil
                                                                              Uniandino</a></li>
                    <li><a href="http://gerenciacampus.uniandes.edu.co">Gerencia de Campus</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <div align="center"><img src ="http://ceu.uniandes.edu.co/Imagenes/nvologo.jpg" alt="First Slide"></div>
          <div class="container">
            <div class="carousel-caption">
              <h1>¡Reporta un daño!</h1>
              <p>¡Empieza a ayudar a tu comunidad!</p>
              <p><a class="btn btn-large btn-primary" href="http://getbootstrap.com/examples/carousel/#">Reportar</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://ceu1.uniandes.edu.co/wordpress/wp-content/uploads/2013/04/Captura-de-pantalla-2013-04-10-a-las-12.42.07.png" alt="Second slide" style="height: 500px; width: 100%; display: block;">
          <div class="container">
            <div class="carousel-caption">
              <h1>¡Creemos una comunidad!</h1>
              <p>Fomentemos el apoyo mutuo. De todos para todos, Uniandes es Comunidad</p>
              <p><a class="btn btn-large btn-primary" href="http://getbootstrap.com/examples/carousel/#">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://ceu1.uniandes.edu.co/wordpress/wp-content/uploads/2013/04/Captura-de-pantalla-2013-04-10-a-las-12.42.07.png" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Third slide" alt="Third slide" style="height: 500px; width: 100%; display: block;">
          <div class="container">
            <div class="carousel-caption">
              <h1>De estudiantes para estudiantes</h1>
              <p>Fixit nació a partir de una iniciativa estudiantil de los representantes de Ingeniería de
                Sistemas y computación, realizada con la ayuda de la ACM.</p>
              <p><a class="btn btn-large btn-primary" href="http://getbootstrap.com/examples/carousel/#">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <!-- img -->
          <h2>Inspirado por estudiantes</h2>
          <p>Nació por una iniciativa de los representantes de Ingeniería de Sistemas Camilo Andrés Ortiz Casas y Diego Serrano Gonzalez. Comenzó como un proyecto, terminó como una forma de unir a Uniandes como comunidad.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/carousel/#">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <!-- img -->
          <h2>Reporta un daño, por una mejor universidad</h2>
          <p>Reportando logras que las demás personas puedan usar mejor las instalaciones de tu universidad. Haz la diferencia, empieza el cambio.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/carousel/#">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <!-- img -->
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/carousel/#">View details »</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <!--img-->
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <!--img-->
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <!--img-->
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="http://getbootstrap.com/examples/carousel/#">Back to top</a></p>
        <p>© 2013 Company, Inc. · <a href="http://getbootstrap.com/examples/carousel/#">Privacy</a> · <a href="http://getbootstrap.com/examples/carousel/#">Terms</a></p>
      </footer>

    </div><!-- /.container -->
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fixit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin-top:50px">

<%= yield %>

</body>
</html>